# config based on examples from SciPy & NumPy repositories, which
# themselves credit an original example by Olivier Grisel at
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
clone_depth: 50
max_jobs: 100

cache:
    - '%LOCALAPPDATA%\pip\Cache'

environment:
    global:
        CONDA_CHANNELS: conda-forge
        CONDA_DEPENDENCIES: pip setuptools wheel cython biopython networkx joblib matplotlib scipy vs2015_runtime pytest mmtf-python GridDataFormats hypothesis pytest-cov codecov chemfiles tqdm tidynamics>=1.0.0 rdkit h5py
        PIP_DEPENDENCIES: gsd==1.9.3 duecredit parmed pyh5md
        DEBUG: "False"
        MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
        APPVEYOR_SAVE_CACHE_ON_ERROR: true
        APPVEYOR_SKIP_FINALIZE_ON_EXIT: true
        TEST_TIMEOUT: 1000
        PYTHON: "C:\\conda"
        # Temporarily fall back to default MINICONDA_VERSION in ci-helpers until https://github.com/MDAnalysis/mdanalysis/issues/2311
        # is fixed in ci-helpers https://github.com/astropy/ci-helpers/issues/406
        # MINICONDA_VERSION: "latest"
        MPLBACKEND: "agg"

    matrix:
        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: 64
          MSVC_VERSION: "Visual Studio 10 Win64"

        - PYTHON_VERSION: 3.8
          PYTHON_ARCH: 64
          MSVC_VERSION: "Visual Studio 10 Win64"

init:
    - ps: Write-Host ${env:PYTHON} ${env:PYTHON_VERSION} ${env:PYTHON_ARCH}
    - ps: Write-Host ${env:APPVEYOR_SCHEDULED_BUILD}
    # cancel build if newer one is submitted; complicated
    # details for getting this to work are credited to JuliaLang
    # developers
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          raise "There are newer queued builds for this pull request, skipping build."
        }

install:
    # set up a conda env
    - ps: git clone -q --depth 1 git://github.com/astropy/ci-helpers.git
    - ps: ci-helpers/appveyor/install-miniconda.ps1
    - ps: $env:PATH = "${env:PYTHON};${env:PYTHON}\Scripts;" + $env:PATH
    # deal with missing stdint.h as previously described
    # see https://github.com/swistakm/pyimgui/blob/master/.appveyor.yml
    - ps: activate test

build_script:
    - cmd: cd package
    - cmd: C:\conda\envs\test\python.exe setup.py develop --no-deps --user 3>&1

test_script:
    - cmd: cd ..\testsuite
    - cmd: C:\conda\envs\test\python.exe setup.py develop --no-deps --user 3>&1
    - cmd: cd MDAnalysisTests
    - cmd: C:\conda\envs\test\Scripts\pytest.exe --cov=MDAnalysis --disable-pytest-warnings 3>&1
    - cmd: codecov

after_build:
    # cache cleanup
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -size +10M -delete
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
    # Show size of cache
    - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
