name: mda-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - chemfiles>=0.10
  - codecov
  - cython
  - docutils
  - fasteners
  - griddataformats
  - gsd
  - h5py>=2.10
  - hypothesis
  - joblib>=0.12
  - mdanalysis-sphinx-theme >=1.3.0
  - matplotlib>=3.2.2
  - mmtf-python
  - mock
  - networkx
  - numpy>=1.23.2
  - pytest
  - python==3.9
  - pytng>=0.2.3
  - scikit-learn
  - scipy
  - pip
  - sphinx <7.0
  - tidynamics>=1.0.0
  - tqdm>=4.43.0
  - sphinxcontrib-bibtex
  - mdaencore
  - waterdynamics
  - pip:
      - mdahole2
      - pathsimanalysis
      - duecredit
      - parmed
      - sphinx-sitemap
      - packaging
      - pyedr>=0.7.0
