# Triage PRs based on modified paths
# Rely on .github/pr_path_labeler.yml
# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage-on-file-paths:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/pr_path_labeler.yml"
        sync-labels: true  # remove labels if file not modified anymore
